#server
server:
  port: 10000

#MyBatis
spring:
  datasource:
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@//localhost:1521/XE
      username: hr
      password: hr

#multipart
  servlet:
    multipart:
      enabled: true
      max-request-size: 40MB
      max-file-size: 40MB
      file-size-threshold: 100MB